"""Pure deterministic options math helpers."""

from sentinel.options.candidates import build_candidates
from sentinel.options.greeks import (
    PositionGreeks,
    delta,
    gamma,
    portfolio_greeks,
    position_greeks,
    rho,
    sum_position_greeks,
    theta,
    vega,
)
from sentinel.options.iv import implied_vol, iv_percentile, iv_rank
from sentinel.options.pricing import bsm_price, crr_price, intrinsic, parity_gap
from sentinel.options.strategies import (
    breakevens,
    build_bear_call_spread,
    build_bear_put_spread,
    build_bull_call_spread,
    build_bull_put_spread,
    build_cash_secured_put,
    build_covered_call,
    build_long_call,
    build_long_put,
    build_long_straddle,
    build_long_strangle,
    max_gain,
    max_loss,
    net_premium,
    payoff_at_expiry,
)

__all__ = [
    "PositionGreeks",
    "breakevens",
    "bsm_price",
    "build_bear_call_spread",
    "build_bear_put_spread",
    "build_bull_call_spread",
    "build_bull_put_spread",
    "build_candidates",
    "build_cash_secured_put",
    "build_covered_call",
    "build_long_call",
    "build_long_put",
    "build_long_straddle",
    "build_long_strangle",
    "crr_price",
    "delta",
    "gamma",
    "implied_vol",
    "intrinsic",
    "iv_percentile",
    "iv_rank",
    "max_gain",
    "max_loss",
    "net_premium",
    "parity_gap",
    "payoff_at_expiry",
    "portfolio_greeks",
    "position_greeks",
    "rho",
    "sum_position_greeks",
    "theta",
    "vega",
]
